### ISSUE TITLE
is this still supported? needs python 3 upgrade

### ISSUE THREAD

**Issue by hannesdelbeke** [fabiangeisler/fg-tools#6]
is this still supported? needs python 3 upgrade
e.g. print "test" now should be print("test")

**Comment by fabiangeisler** [comment]
Hi @hannesdelbeke !
Thanks for your interest in the tools! As you can see from the commit history, there has been no development for quite some time on the tools. Since I moved from modelling to pipeline development, my need for the tools has steadily declined. I have no intention of maintaining the code for the time being. 
That said, it should not be hard to convert the scripts to be python 3 compliant and I will happily accept pull requests for it.
